/**
 * Hotel Amenities & Services Data
 * Includes special offers for valet customers
 */

import { 
  Utensils, Coffee, Dumbbell, Sparkles, Wind, Flame,
  Wine, Bell, Wifi, Car, Phone, MapPin, Clock,
  Gift, Heart, Star, Briefcase, Shirt, Baby
} from 'lucide-react';

// Special offers for valet guests (shown prominently)
export const SPECIAL_OFFERS = [
  {
    id: 'dinner-discount',
    title: '15% Off Dinner',
    subtitle: 'fl.2 Restaurant',
    description: 'Exclusive valet guest discount on your dining experience tonight',
    code: 'VALET15',
    validUntil: 'Today only',
    icon: Utensils,
    color: 'from-amber-500 to-orange-500',
    featured: true,
  },
  {
    id: 'spa-special',
    title: '$25 Off Spa',
    subtitle: 'Health Club & Spa',
    description: 'Complimentary upgrade to aromatherapy with any massage booking',
    code: 'VALETSPA',
    validUntil: 'This stay',
    icon: Sparkles,
    color: 'from-purple-500 to-pink-500',
    featured: true,
  },
  {
    id: 'wine-happy',
    title: 'Happy Hour Special',
    subtitle: "Andy's Wine Bar",
    description: '2-for-1 on select wines, 4PM - 7PM',
    code: null,
    validUntil: '4PM - 7PM',
    icon: Wine,
    color: 'from-rose-500 to-red-500',
    featured: false,
  },
];

// Main amenity categories
export const AMENITY_CATEGORIES = [
  { id: 'all', name: 'All', icon: Star },
  { id: 'dining', name: 'Dining', icon: Utensils },
  { id: 'wellness', name: 'Wellness', icon: Heart },
  { id: 'services', name: 'Services', icon: Bell },
  { id: 'business', name: 'Business', icon: Briefcase },
];

// Full amenities list
export const AMENITIES = [
  // Dining
  {
    id: 'fl2-restaurant',
    category: 'dining',
    name: 'fl.2 Restaurant',
    tagline: 'Modern American Cuisine',
    description: 'Fresh farm eggs, locally grown produce, home-baked goods, and finely crafted cocktails. Designed by acclaimed Spanish designer Lázaro Rosa-Violán.',
    floor: '2nd Floor',
    hours: '7:00 AM - 10:00 PM',
    phone: '(412) 773-8848',
    icon: Utensils,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80',
    features: ['Farm-to-Table', 'Craft Cocktails', 'Weekend Brunch', 'Private Events'],
    reservationRequired: true,
    priceRange: '$$$',
    specialOffer: {
      text: '15% off for valet guests',
      code: 'VALET15',
    },
  },
  {
    id: 'andys-wine-bar',
    category: 'dining',
    name: "Andy's Wine Bar",
    tagline: 'Curated Wines & Small Plates',
    description: 'Named after Pittsburgh native Andy Warhol, featuring an impressive selection of wines and artisan small plates in an intimate setting.',
    floor: 'Lobby Level',
    hours: '4:00 PM - 11:00 PM',
    phone: '(412) 773-8800',
    icon: Wine,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80',
    features: ['Wine Flights', 'Cheese Boards', 'Live Music Fridays'],
    reservationRequired: false,
    priceRange: '$$',
    specialOffer: {
      text: 'Happy Hour 4-7PM',
      code: null,
    },
  },
  {
    id: 'starbucks',
    category: 'dining',
    name: 'Starbucks',
    tagline: 'Premium Coffee',
    description: 'Start your morning with your favorite coffee and quick breakfast options in our main lobby location.',
    floor: 'Main Lobby',
    hours: '6:00 AM - 6:00 PM',
    phone: '(412) 773-8800',
    icon: Coffee,
    image: 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800&q=80',
    features: ['Premium Coffee', 'Pastries', 'Grab & Go'],
    reservationRequired: false,
    priceRange: '$',
  },
  {
    id: 'room-service',
    category: 'dining',
    name: 'In-Room Dining',
    tagline: '24-Hour Service',
    description: 'Enjoy quality meals from the comfort of your room, any time of day or night. Full menu available.',
    floor: 'Your Room',
    hours: '24/7',
    phone: 'Dial 0',
    icon: Bell,
    image: 'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=800&q=80',
    features: ['24/7 Available', 'Full Menu', 'Special Requests', 'Dietary Options'],
    reservationRequired: false,
    priceRange: '$$',
  },
  
  // Wellness
  {
    id: 'spa',
    category: 'wellness',
    name: 'Health Club & Spa',
    tagline: 'Urban Sanctuary',
    description: 'Release tension and restore radiance with aromatherapy massages, hot stone treatments, facials, and body scrubs in our tranquil spa.',
    floor: 'Lower Level',
    hours: '6:00 AM - 9:00 PM',
    phone: '(412) 773-8882',
    icon: Sparkles,
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80',
    features: ['Swedish Massage', 'Aromatherapy', 'Hot Stone', 'Facials', 'Body Scrubs'],
    reservationRequired: true,
    priceRange: '$$$',
    specialOffer: {
      text: '$25 off any treatment',
      code: 'VALETSPA',
    },
  },
  {
    id: 'fitness',
    category: 'wellness',
    name: 'Fitness Center',
    tagline: '6,000 Sq Ft Facility',
    description: 'Dynamic downtown views from floor-to-ceiling windows energize your cardio workout. State-of-the-art equipment and personal trainers available.',
    floor: 'Lower Level',
    hours: '24/7 Access',
    phone: '(412) 773-8882',
    icon: Dumbbell,
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
    features: ['Cardio Equipment', 'Free Weights', 'Personal Training', 'Towel Service'],
    reservationRequired: false,
    priceRange: 'Complimentary',
  },
  {
    id: 'sauna',
    category: 'wellness',
    name: 'Cedar Dry Sauna',
    tagline: 'Detox & Relax',
    description: 'Complete your wellness journey with a session in our authentic dry cedar sauna for detoxification and relaxation.',
    floor: 'Lower Level (Spa)',
    hours: '6:00 AM - 9:00 PM',
    phone: '(412) 773-8882',
    icon: Flame,
    image: 'https://images.unsplash.com/photo-1554244933-d876deb6b2ff?w=800&q=80',
    features: ['Dry Heat Therapy', 'Detoxification', 'Muscle Recovery'],
    reservationRequired: false,
    priceRange: 'Complimentary',
  },
  {
    id: 'steam',
    category: 'wellness',
    name: 'Eucalyptus Steam Room',
    tagline: 'Respiratory Wellness',
    description: 'Breathe in the therapeutic eucalyptus vapors while tension melts away in our steam sanctuary.',
    floor: 'Lower Level (Spa)',
    hours: '6:00 AM - 9:00 PM',
    phone: '(412) 773-8882',
    icon: Wind,
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
    features: ['Eucalyptus Infused', 'Respiratory Benefits', 'Deep Relaxation'],
    reservationRequired: false,
    priceRange: 'Complimentary',
  },
  
  // Services
  {
    id: 'concierge',
    category: 'services',
    name: 'Concierge Services',
    tagline: 'At Your Service',
    description: 'Our expert concierge team can assist with restaurant reservations, theater tickets, tours, and any special requests.',
    floor: 'Main Lobby',
    hours: '24/7',
    phone: 'Dial 0',
    icon: Bell,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    features: ['Reservations', 'Tickets', 'Tours', 'Transportation'],
    reservationRequired: false,
    priceRange: 'Complimentary',
  },
  {
    id: 'valet',
    category: 'services',
    name: 'Valet Parking',
    tagline: 'Premium Service',
    description: 'Your vehicle is secured in our climate-controlled garage with 24/7 attendants. Request retrieval anytime.',
    floor: 'Main Entrance',
    hours: '24/7',
    phone: '(412) 773-8848',
    icon: Car,
    image: 'https://images.unsplash.com/photo-1486006920555-c77dcf18193c?w=800&q=80',
    features: ['24/7 Service', 'Climate Controlled', 'EV Charging Available'],
    reservationRequired: false,
    priceRange: '$36/day',
  },
  {
    id: 'wifi',
    category: 'services',
    name: 'High-Speed WiFi',
    tagline: 'Stay Connected',
    description: 'Complimentary high-speed internet access throughout the hotel and in all guest rooms.',
    floor: 'Hotel-Wide',
    hours: 'Always Available',
    phone: null,
    icon: Wifi,
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80',
    features: ['Complimentary', 'High-Speed', 'Secure Network'],
    reservationRequired: false,
    priceRange: 'Complimentary',
  },
  {
    id: 'laundry',
    category: 'services',
    name: 'Laundry & Dry Cleaning',
    tagline: 'Same-Day Service',
    description: 'Professional laundry and dry cleaning services with same-day delivery available.',
    floor: 'Request from Room',
    hours: 'Pickup by 9AM',
    phone: 'Dial 0',
    icon: Shirt,
    image: 'https://images.unsplash.com/photo-1545173168-9f1947eebb7f?w=800&q=80',
    features: ['Same-Day Service', 'Pressing', 'Shoe Shine'],
    reservationRequired: false,
    priceRange: '$$',
  },
  
  // Business
  {
    id: 'business-center',
    category: 'business',
    name: 'Business Center',
    tagline: 'Work & Connect',
    description: 'Fully equipped business center with computers, printing, and private meeting spaces.',
    floor: 'Lower Level',
    hours: '24/7 Access',
    phone: '(412) 773-8800',
    icon: Briefcase,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    features: ['Computers', 'Printing', 'Scanning', 'Fax'],
    reservationRequired: false,
    priceRange: 'Complimentary',
  },
  {
    id: 'meeting-rooms',
    category: 'business',
    name: 'Meeting Rooms',
    tagline: 'Private & Professional',
    description: 'Various meeting spaces from intimate boardrooms to grand ballrooms for events up to 500 guests.',
    floor: 'Multiple Floors',
    hours: 'By Reservation',
    phone: '(412) 773-8800',
    icon: Briefcase,
    image: 'https://images.unsplash.com/photo-1431540015161-0bf868a2d407?w=800&q=80',
    features: ['AV Equipment', 'Catering Available', 'Natural Light'],
    reservationRequired: true,
    priceRange: 'Contact for rates',
  },
];

// Quick actions shown on main screen
export const QUICK_ACTIONS = [
  { id: 'restaurant', name: 'Reserve Table', icon: Utensils, route: 'reservations' },
  { id: 'spa', name: 'Book Spa', icon: Sparkles, route: 'spa-booking' },
  { id: 'room-service', name: 'Room Service', icon: Bell, action: 'call', phone: '0' },
  { id: 'concierge', name: 'Concierge', icon: Phone, action: 'call', phone: '(412) 773-8800' },
];

// Nearby attractions
export const NEARBY_PLACES = [
  {
    id: 'warhol',
    name: 'Andy Warhol Museum',
    type: 'Museum',
    distance: '0.8 miles',
    walkTime: '15 min',
    description: 'World\'s largest museum dedicated to a single artist',
    image: 'https://images.unsplash.com/photo-1594794312433-05a2a45a0a77?w=400&q=80',
  },
  {
    id: 'market-square',
    name: 'Market Square',
    type: 'Shopping',
    distance: '0.3 miles',
    walkTime: '5 min',
    description: 'Historic downtown square with shops & restaurants',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&q=80',
  },
  {
    id: 'point-state',
    name: 'Point State Park',
    type: 'Park',
    distance: '0.5 miles',
    walkTime: '10 min',
    description: 'Iconic fountain at the confluence of three rivers',
    image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=400&q=80',
  },
  {
    id: 'ppg',
    name: 'PPG Place',
    type: 'Architecture',
    distance: '0.2 miles',
    walkTime: '3 min',
    description: 'Stunning glass castle architecture & shopping',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&q=80',
  },
];

export default {
  SPECIAL_OFFERS,
  AMENITY_CATEGORIES,
  AMENITIES,
  QUICK_ACTIONS,
  NEARBY_PLACES,
};
